# Домашнаяя работа №1

In [451]:
import numpy as np

### Создание массивов

In [452]:
n1 = np.array([1, 2, 3])     # создание одномерного массива
print(n1)

[1 2 3]


In [453]:
n2 = np.array([[1, 1, 1] , [2, 2, 2], [3, 3, 3]])    # создание двумерного массива
print(n2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [454]:
n3 = np.array([[[1, 2, 1] , [2, 3, 2], [3, 4, 3]], [[4, 5, 4], [5, 6, 5], [6, 7, 6]]])    # создание трехмерного массива
print(n3)

[[[1 2 1]
  [2 3 2]
  [3 4 3]]

 [[4 5 4]
  [5 6 5]
  [6 7 6]]]


In [455]:
zer = np.zeros((2, 6, 5), int)    # матрица из нулей 
print(zer)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [456]:
one = np.ones((3, 5))    # матрица из единиц
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [457]:
arang = np.arange(2, 23, 4).reshape((2, 3))   # создание одномерной матрицы от 2 до 23 с шагом 4 и изменение её в двумерную с размером (2, 3)
print(arang)

[[ 2  6 10]
 [14 18 22]]


In [458]:
emp = np.empty((3, 6))
print(emp)

[[4.67296746e-307 1.69121096e-306 1.33511969e-306 9.79101082e-307
  1.33511969e-306 1.11256817e-306]
 [1.06811422e-306 1.42417221e-306 1.11260619e-306 8.90094053e-307
  1.86919378e-306 1.06809792e-306]
 [1.37962456e-306 1.69111861e-306 1.78020169e-306 1.37961777e-306
  7.56599807e-307 7.56599806e-307]]


### Получение размера матрицы

In [459]:
print(n2.shape)
print(zer.shape)
print(arang.shape)

(3, 3)
(2, 6, 5)
(2, 3)


### Получение типа данных матрицы

In [460]:
print(zer.dtype)
print(one.dtype)

int32
float64


### Индексирование матрицы

In [461]:
n3 = np.array([[[1, 2, 1] , [2, 3, 2], [3, 4, 3]], [[4, 5, 4], [5, 6, 5], [6, 7, 6]], [[7, 8, 7], [8, 9, 8], [9, 0 , 9]]])    # создание трехмерного массива
print(n3[1,2,1])  #  получние элемента

7


In [462]:
n3 = np.array([[[1, 2, 1] , [2, 3, 2], [3, 4, 3]], [[4, 5, 4], [5, 6, 5], [6, 7, 6]], [[7, 8, 7], [8, 9, 8], [9, 0 , 9]]])    # создание трехмерного массива
print(n3)
print("-------------------------------")
print(n3[1:, :2, 1:2])  # получение подмассива

[[[1 2 1]
  [2 3 2]
  [3 4 3]]

 [[4 5 4]
  [5 6 5]
  [6 7 6]]

 [[7 8 7]
  [8 9 8]
  [9 0 9]]]
-------------------------------
[[[5]
  [6]]

 [[8]
  [9]]]


### Векторные операции с массивами

In [463]:
a = np.array([1, 3, 5, 7])
b = np.array([2, 4, 6, 8])
print(a+b)
print(a*b)
print(a**3)

[ 3  7 11 15]
[ 2 12 30 56]
[  1  27 125 343]


In [464]:
print(a.mean())
print(a.min())
print(a.max())

4.0
1
7


In [ ]:
b = b.reshape((2, 2))
print(b)
print(b.min())  # минимальное значение матрицы
print(b.min(axis = 1)) # минимальное значение по строкам

[[2 4]
 [6 8]]
2
[2 6]
